QT -= gui
QT +=network
QT += sql
CONFIG += c++17 console
CONFIG -= app_bundle

# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0
INCLUDEPATH += "D:\ATM\ANUL 2\Sem 2\POO Proiect\Corbu Ionut-Daniel + Toader Radu-Marian\IORA_Server\poco\Net\include"
INCLUDEPATH += "D:\ATM\ANUL 2\Sem 2\POO Proiect\Corbu Ionut-Daniel + Toader Radu-Marian\IORA_Server\poco\Foundation\include"
SOURCES += \
        absmesaj.cpp \
        canal.cpp \
        chat.cpp \
        database.cpp \
        decoder.cpp \
        emailsender.cpp \
        encoder.cpp \
        file.cpp \
        main.cpp \
        meet.cpp \
        mesaj.cpp \
        qtcpserver.cpp \
        solver.cpp \


# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

HEADERS += \
    IMesaj.h \
    absmesaj.h \
    canal.h \
    chat.h \
    database.h \
    decoder.h \
    emailsender.h \
    encoder.h \
    file.h \
    meet.h \
    mesaj.h \
    poco/Foundation/include/Poco/ASCIIEncoding.h \
    poco/Foundation/include/Poco/AbstractCache.h \
    poco/Foundation/include/Poco/AbstractDelegate.h \
    poco/Foundation/include/Poco/AbstractEvent.h \
    poco/Foundation/include/Poco/AbstractObserver.h \
    poco/Foundation/include/Poco/AbstractPriorityDelegate.h \
    poco/Foundation/include/Poco/AbstractStrategy.h \
    poco/Foundation/include/Poco/AccessExpirationDecorator.h \
    poco/Foundation/include/Poco/AccessExpireCache.h \
    poco/Foundation/include/Poco/AccessExpireLRUCache.h \
    poco/Foundation/include/Poco/AccessExpireStrategy.h \
    poco/Foundation/include/Poco/ActiveDispatcher.h \
    poco/Foundation/include/Poco/ActiveMethod.h \
    poco/Foundation/include/Poco/ActiveResult.h \
    poco/Foundation/include/Poco/ActiveRunnable.h \
    poco/Foundation/include/Poco/ActiveStarter.h \
    poco/Foundation/include/Poco/Activity.h \
    poco/Foundation/include/Poco/Alignment.h \
    poco/Foundation/include/Poco/Any.h \
    poco/Foundation/include/Poco/ArchiveStrategy.h \
    poco/Foundation/include/Poco/Array.h \
    poco/Foundation/include/Poco/Ascii.h \
    poco/Foundation/include/Poco/AsyncChannel.h \
    poco/Foundation/include/Poco/AtomicCounter.h \
    poco/Foundation/include/Poco/AtomicFlag.h \
    poco/Foundation/include/Poco/AutoPtr.h \
    poco/Foundation/include/Poco/AutoReleasePool.h \
    poco/Foundation/include/Poco/Base32Decoder.h \
    poco/Foundation/include/Poco/Base32Encoder.h \
    poco/Foundation/include/Poco/Base64Decoder.h \
    poco/Foundation/include/Poco/Base64Encoder.h \
    poco/Foundation/include/Poco/BasicEvent.h \
    poco/Foundation/include/Poco/BinaryReader.h \
    poco/Foundation/include/Poco/BinaryWriter.h \
    poco/Foundation/include/Poco/Buffer.h \
    poco/Foundation/include/Poco/BufferAllocator.h \
    poco/Foundation/include/Poco/BufferedBidirectionalStreamBuf.h \
    poco/Foundation/include/Poco/BufferedStreamBuf.h \
    poco/Foundation/include/Poco/Bugcheck.h \
    poco/Foundation/include/Poco/ByteOrder.h \
    poco/Foundation/include/Poco/Channel.h \
    poco/Foundation/include/Poco/Checksum.h \
    poco/Foundation/include/Poco/ClassLibrary.h \
    poco/Foundation/include/Poco/ClassLoader.h \
    poco/Foundation/include/Poco/Clock.h \
    poco/Foundation/include/Poco/Condition.h \
    poco/Foundation/include/Poco/Config.h \
    poco/Foundation/include/Poco/Configurable.h \
    poco/Foundation/include/Poco/ConsoleChannel.h \
    poco/Foundation/include/Poco/CountingStream.h \
    poco/Foundation/include/Poco/DataURIStream.h \
    poco/Foundation/include/Poco/DataURIStreamFactory.h \
    poco/Foundation/include/Poco/DateTime.h \
    poco/Foundation/include/Poco/DateTimeFormat.h \
    poco/Foundation/include/Poco/DateTimeFormatter.h \
    poco/Foundation/include/Poco/DateTimeParser.h \
    poco/Foundation/include/Poco/Debugger.h \
    poco/Foundation/include/Poco/DefaultStrategy.h \
    poco/Foundation/include/Poco/DeflatingStream.h \
    poco/Foundation/include/Poco/Delegate.h \
    poco/Foundation/include/Poco/DigestEngine.h \
    poco/Foundation/include/Poco/DigestStream.h \
    poco/Foundation/include/Poco/DirectoryIterator.h \
    poco/Foundation/include/Poco/DirectoryIteratorStrategy.h \
    poco/Foundation/include/Poco/DirectoryIterator_UNIX.h \
    poco/Foundation/include/Poco/DirectoryIterator_WIN32U.h \
    poco/Foundation/include/Poco/DirectoryWatcher.h \
    poco/Foundation/include/Poco/Dynamic/Pair.h \
    poco/Foundation/include/Poco/Dynamic/Struct.h \
    poco/Foundation/include/Poco/Dynamic/Var.h \
    poco/Foundation/include/Poco/Dynamic/VarHolder.h \
    poco/Foundation/include/Poco/Dynamic/VarIterator.h \
    poco/Foundation/include/Poco/DynamicAny.h \
    poco/Foundation/include/Poco/DynamicAnyHolder.h \
    poco/Foundation/include/Poco/DynamicFactory.h \
    poco/Foundation/include/Poco/DynamicStruct.h \
    poco/Foundation/include/Poco/Environment.h \
    poco/Foundation/include/Poco/Environment_UNIX.h \
    poco/Foundation/include/Poco/Environment_VX.h \
    poco/Foundation/include/Poco/Environment_WIN32U.h \
    poco/Foundation/include/Poco/Environment_WINCE.h \
    poco/Foundation/include/Poco/Error.h \
    poco/Foundation/include/Poco/ErrorHandler.h \
    poco/Foundation/include/Poco/Event.h \
    poco/Foundation/include/Poco/EventArgs.h \
    poco/Foundation/include/Poco/EventChannel.h \
    poco/Foundation/include/Poco/EventLogChannel.h \
    poco/Foundation/include/Poco/Event_POSIX.h \
    poco/Foundation/include/Poco/Event_VX.h \
    poco/Foundation/include/Poco/Event_WIN32.h \
    poco/Foundation/include/Poco/Exception.h \
    poco/Foundation/include/Poco/ExpirationDecorator.h \
    poco/Foundation/include/Poco/Expire.h \
    poco/Foundation/include/Poco/ExpireCache.h \
    poco/Foundation/include/Poco/ExpireLRUCache.h \
    poco/Foundation/include/Poco/ExpireStrategy.h \
    poco/Foundation/include/Poco/FIFOBuffer.h \
    poco/Foundation/include/Poco/FIFOBufferStream.h \
    poco/Foundation/include/Poco/FIFOEvent.h \
    poco/Foundation/include/Poco/FIFOStrategy.h \
    poco/Foundation/include/Poco/FPEnvironment.h \
    poco/Foundation/include/Poco/FPEnvironment_C99.h \
    poco/Foundation/include/Poco/FPEnvironment_DEC.h \
    poco/Foundation/include/Poco/FPEnvironment_DUMMY.h \
    poco/Foundation/include/Poco/FPEnvironment_QNX.h \
    poco/Foundation/include/Poco/FPEnvironment_SUN.h \
    poco/Foundation/include/Poco/FPEnvironment_WIN32.h \
    poco/Foundation/include/Poco/File.h \
    poco/Foundation/include/Poco/FileChannel.h \
    poco/Foundation/include/Poco/FileStream.h \
    poco/Foundation/include/Poco/FileStreamFactory.h \
    poco/Foundation/include/Poco/FileStream_POSIX.h \
    poco/Foundation/include/Poco/FileStream_WIN32.h \
    poco/Foundation/include/Poco/File_UNIX.h \
    poco/Foundation/include/Poco/File_VX.h \
    poco/Foundation/include/Poco/File_WIN32U.h \
    poco/Foundation/include/Poco/File_WINCE.h \
    poco/Foundation/include/Poco/Format.h \
    poco/Foundation/include/Poco/Formatter.h \
    poco/Foundation/include/Poco/FormattingChannel.h \
    poco/Foundation/include/Poco/Foundation.h \
    poco/Foundation/include/Poco/FunctionDelegate.h \
    poco/Foundation/include/Poco/FunctionPriorityDelegate.h \
    poco/Foundation/include/Poco/Glob.h \
    poco/Foundation/include/Poco/HMACEngine.h \
    poco/Foundation/include/Poco/Hash.h \
    poco/Foundation/include/Poco/HashFunction.h \
    poco/Foundation/include/Poco/HashMap.h \
    poco/Foundation/include/Poco/HashSet.h \
    poco/Foundation/include/Poco/HashStatistic.h \
    poco/Foundation/include/Poco/HashTable.h \
    poco/Foundation/include/Poco/HexBinaryDecoder.h \
    poco/Foundation/include/Poco/HexBinaryEncoder.h \
    poco/Foundation/include/Poco/InflatingStream.h \
    poco/Foundation/include/Poco/Instantiator.h \
    poco/Foundation/include/Poco/JSONString.h \
    poco/Foundation/include/Poco/KeyValueArgs.h \
    poco/Foundation/include/Poco/LRUCache.h \
    poco/Foundation/include/Poco/LRUStrategy.h \
    poco/Foundation/include/Poco/Latin1Encoding.h \
    poco/Foundation/include/Poco/Latin2Encoding.h \
    poco/Foundation/include/Poco/Latin9Encoding.h \
    poco/Foundation/include/Poco/LineEndingConverter.h \
    poco/Foundation/include/Poco/LinearHashTable.h \
    poco/Foundation/include/Poco/ListMap.h \
    poco/Foundation/include/Poco/LocalDateTime.h \
    poco/Foundation/include/Poco/LogFile.h \
    poco/Foundation/include/Poco/LogFile_STD.h \
    poco/Foundation/include/Poco/LogFile_WIN32U.h \
    poco/Foundation/include/Poco/LogStream.h \
    poco/Foundation/include/Poco/Logger.h \
    poco/Foundation/include/Poco/LoggingFactory.h \
    poco/Foundation/include/Poco/LoggingRegistry.h \
    poco/Foundation/include/Poco/MD4Engine.h \
    poco/Foundation/include/Poco/MD5Engine.h \
    poco/Foundation/include/Poco/Manifest.h \
    poco/Foundation/include/Poco/MemoryPool.h \
    poco/Foundation/include/Poco/MemoryStream.h \
    poco/Foundation/include/Poco/Message.h \
    poco/Foundation/include/Poco/MetaObject.h \
    poco/Foundation/include/Poco/MetaProgramming.h \
    poco/Foundation/include/Poco/Mutex.h \
    poco/Foundation/include/Poco/Mutex_POSIX.h \
    poco/Foundation/include/Poco/Mutex_VX.h \
    poco/Foundation/include/Poco/Mutex_WIN32.h \
    poco/Foundation/include/Poco/Mutex_WINCE.h \
    poco/Foundation/include/Poco/NObserver.h \
    poco/Foundation/include/Poco/NamedEvent.h \
    poco/Foundation/include/Poco/NamedEvent_Android.h \
    poco/Foundation/include/Poco/NamedEvent_UNIX.h \
    poco/Foundation/include/Poco/NamedEvent_WIN32U.h \
    poco/Foundation/include/Poco/NamedMutex.h \
    poco/Foundation/include/Poco/NamedMutex_Android.h \
    poco/Foundation/include/Poco/NamedMutex_UNIX.h \
    poco/Foundation/include/Poco/NamedMutex_WIN32U.h \
    poco/Foundation/include/Poco/NamedTuple.h \
    poco/Foundation/include/Poco/NestedDiagnosticContext.h \
    poco/Foundation/include/Poco/Notification.h \
    poco/Foundation/include/Poco/NotificationCenter.h \
    poco/Foundation/include/Poco/NotificationQueue.h \
    poco/Foundation/include/Poco/NotificationStrategy.h \
    poco/Foundation/include/Poco/NullChannel.h \
    poco/Foundation/include/Poco/NullStream.h \
    poco/Foundation/include/Poco/Nullable.h \
    poco/Foundation/include/Poco/NumberFormatter.h \
    poco/Foundation/include/Poco/NumberParser.h \
    poco/Foundation/include/Poco/NumericString.h \
    poco/Foundation/include/Poco/ObjectPool.h \
    poco/Foundation/include/Poco/Observer.h \
    poco/Foundation/include/Poco/Optional.h \
    poco/Foundation/include/Poco/OrderedMap.h \
    poco/Foundation/include/Poco/OrderedSet.h \
    poco/Foundation/include/Poco/PBKDF2Engine.h \
    poco/Foundation/include/Poco/Path.h \
    poco/Foundation/include/Poco/Path_UNIX.h \
    poco/Foundation/include/Poco/Path_WIN32U.h \
    poco/Foundation/include/Poco/Path_WINCE.h \
    poco/Foundation/include/Poco/PatternFormatter.h \
    poco/Foundation/include/Poco/Pipe.h \
    poco/Foundation/include/Poco/PipeImpl.h \
    poco/Foundation/include/Poco/PipeImpl_DUMMY.h \
    poco/Foundation/include/Poco/PipeImpl_POSIX.h \
    poco/Foundation/include/Poco/PipeImpl_WIN32.h \
    poco/Foundation/include/Poco/PipeStream.h \
    poco/Foundation/include/Poco/Platform.h \
    poco/Foundation/include/Poco/Platform_POSIX.h \
    poco/Foundation/include/Poco/Platform_VX.h \
    poco/Foundation/include/Poco/Platform_WIN32.h \
    poco/Foundation/include/Poco/Poco.h \
    poco/Foundation/include/Poco/PriorityDelegate.h \
    poco/Foundation/include/Poco/PriorityEvent.h \
    poco/Foundation/include/Poco/PriorityExpire.h \
    poco/Foundation/include/Poco/PriorityNotificationQueue.h \
    poco/Foundation/include/Poco/PriorityStrategy.h \
    poco/Foundation/include/Poco/Process.h \
    poco/Foundation/include/Poco/Process_UNIX.h \
    poco/Foundation/include/Poco/Process_VX.h \
    poco/Foundation/include/Poco/Process_WIN32U.h \
    poco/Foundation/include/Poco/Process_WINCE.h \
    poco/Foundation/include/Poco/PurgeStrategy.h \
    poco/Foundation/include/Poco/RWLock.h \
    poco/Foundation/include/Poco/RWLock_Android.h \
    poco/Foundation/include/Poco/RWLock_POSIX.h \
    poco/Foundation/include/Poco/RWLock_VX.h \
    poco/Foundation/include/Poco/RWLock_WIN32.h \
    poco/Foundation/include/Poco/RWLock_WINCE.h \
    poco/Foundation/include/Poco/Random.h \
    poco/Foundation/include/Poco/RandomStream.h \
    poco/Foundation/include/Poco/RecursiveDirectoryIterator.h \
    poco/Foundation/include/Poco/RecursiveDirectoryIteratorImpl.h \
    poco/Foundation/include/Poco/RefCountedObject.h \
    poco/Foundation/include/Poco/RegularExpression.h \
    poco/Foundation/include/Poco/RotateStrategy.h \
    poco/Foundation/include/Poco/Runnable.h \
    poco/Foundation/include/Poco/RunnableAdapter.h \
    poco/Foundation/include/Poco/SHA1Engine.h \
    poco/Foundation/include/Poco/SHA2Engine.h \
    poco/Foundation/include/Poco/ScopedLock.h \
    poco/Foundation/include/Poco/ScopedUnlock.h \
    poco/Foundation/include/Poco/Semaphore.h \
    poco/Foundation/include/Poco/Semaphore_POSIX.h \
    poco/Foundation/include/Poco/Semaphore_VX.h \
    poco/Foundation/include/Poco/Semaphore_WIN32.h \
    poco/Foundation/include/Poco/SharedLibrary.h \
    poco/Foundation/include/Poco/SharedLibrary_HPUX.h \
    poco/Foundation/include/Poco/SharedLibrary_UNIX.h \
    poco/Foundation/include/Poco/SharedLibrary_VX.h \
    poco/Foundation/include/Poco/SharedLibrary_WIN32U.h \
    poco/Foundation/include/Poco/SharedMemory.h \
    poco/Foundation/include/Poco/SharedMemory_DUMMY.h \
    poco/Foundation/include/Poco/SharedMemory_POSIX.h \
    poco/Foundation/include/Poco/SharedMemory_WIN32.h \
    poco/Foundation/include/Poco/SharedPtr.h \
    poco/Foundation/include/Poco/SignalHandler.h \
    poco/Foundation/include/Poco/SimpleFileChannel.h \
    poco/Foundation/include/Poco/SimpleHashTable.h \
    poco/Foundation/include/Poco/SingletonHolder.h \
    poco/Foundation/include/Poco/SortedDirectoryIterator.h \
    poco/Foundation/include/Poco/SplitterChannel.h \
    poco/Foundation/include/Poco/Stopwatch.h \
    poco/Foundation/include/Poco/StrategyCollection.h \
    poco/Foundation/include/Poco/StreamChannel.h \
    poco/Foundation/include/Poco/StreamConverter.h \
    poco/Foundation/include/Poco/StreamCopier.h \
    poco/Foundation/include/Poco/StreamTokenizer.h \
    poco/Foundation/include/Poco/StreamUtil.h \
    poco/Foundation/include/Poco/String.h \
    poco/Foundation/include/Poco/StringTokenizer.h \
    poco/Foundation/include/Poco/SynchronizedObject.h \
    poco/Foundation/include/Poco/SyslogChannel.h \
    poco/Foundation/include/Poco/Task.h \
    poco/Foundation/include/Poco/TaskManager.h \
    poco/Foundation/include/Poco/TaskNotification.h \
    poco/Foundation/include/Poco/TeeStream.h \
    poco/Foundation/include/Poco/TemporaryFile.h \
    poco/Foundation/include/Poco/TextBufferIterator.h \
    poco/Foundation/include/Poco/TextConverter.h \
    poco/Foundation/include/Poco/TextEncoding.h \
    poco/Foundation/include/Poco/TextIterator.h \
    poco/Foundation/include/Poco/Thread.h \
    poco/Foundation/include/Poco/ThreadLocal.h \
    poco/Foundation/include/Poco/ThreadPool.h \
    poco/Foundation/include/Poco/ThreadTarget.h \
    poco/Foundation/include/Poco/Thread_POSIX.h \
    poco/Foundation/include/Poco/Thread_VX.h \
    poco/Foundation/include/Poco/Thread_WIN32.h \
    poco/Foundation/include/Poco/Thread_WINCE.h \
    poco/Foundation/include/Poco/TimedNotificationQueue.h \
    poco/Foundation/include/Poco/Timer.h \
    poco/Foundation/include/Poco/Timespan.h \
    poco/Foundation/include/Poco/Timestamp.h \
    poco/Foundation/include/Poco/Timezone.h \
    poco/Foundation/include/Poco/Token.h \
    poco/Foundation/include/Poco/Tuple.h \
    poco/Foundation/include/Poco/TypeList.h \
    poco/Foundation/include/Poco/Types.h \
    poco/Foundation/include/Poco/URI.h \
    poco/Foundation/include/Poco/URIStreamFactory.h \
    poco/Foundation/include/Poco/URIStreamOpener.h \
    poco/Foundation/include/Poco/UTF16Encoding.h \
    poco/Foundation/include/Poco/UTF32Encoding.h \
    poco/Foundation/include/Poco/UTF8Encoding.h \
    poco/Foundation/include/Poco/UTF8String.h \
    poco/Foundation/include/Poco/UTFString.h \
    poco/Foundation/include/Poco/UUID.h \
    poco/Foundation/include/Poco/UUIDGenerator.h \
    poco/Foundation/include/Poco/UnWindows.h \
    poco/Foundation/include/Poco/UnbufferedStreamBuf.h \
    poco/Foundation/include/Poco/Unicode.h \
    poco/Foundation/include/Poco/UnicodeConverter.h \
    poco/Foundation/include/Poco/UniqueAccessExpireCache.h \
    poco/Foundation/include/Poco/UniqueAccessExpireLRUCache.h \
    poco/Foundation/include/Poco/UniqueAccessExpireStrategy.h \
    poco/Foundation/include/Poco/UniqueExpireCache.h \
    poco/Foundation/include/Poco/UniqueExpireLRUCache.h \
    poco/Foundation/include/Poco/UniqueExpireStrategy.h \
    poco/Foundation/include/Poco/ValidArgs.h \
    poco/Foundation/include/Poco/Version.h \
    poco/Foundation/include/Poco/Void.h \
    poco/Foundation/include/Poco/Windows1250Encoding.h \
    poco/Foundation/include/Poco/Windows1251Encoding.h \
    poco/Foundation/include/Poco/Windows1252Encoding.h \
    poco/Foundation/include/Poco/WindowsConsoleChannel.h \
    poco/Foundation/include/Poco/ordered_hash.h \
    poco/Foundation/include/Poco/ordered_map.h \
    poco/Foundation/include/Poco/ordered_set.h \
    poco/Foundation/include/Poco/zconf.h \
    poco/Foundation/include/Poco/zlib.h \
    poco/Net/include/Poco/Net/AbstractHTTPRequestHandler.h \
    poco/Net/include/Poco/Net/DNS.h \
    poco/Net/include/Poco/Net/DatagramSocket.h \
    poco/Net/include/Poco/Net/DatagramSocketImpl.h \
    poco/Net/include/Poco/Net/DialogSocket.h \
    poco/Net/include/Poco/Net/EscapeHTMLStream.h \
    poco/Net/include/Poco/Net/FTPClientSession.h \
    poco/Net/include/Poco/Net/FTPStreamFactory.h \
    poco/Net/include/Poco/Net/FilePartSource.h \
    poco/Net/include/Poco/Net/HTMLForm.h \
    poco/Net/include/Poco/Net/HTTPAuthenticationParams.h \
    poco/Net/include/Poco/Net/HTTPBasicCredentials.h \
    poco/Net/include/Poco/Net/HTTPBasicStreamBuf.h \
    poco/Net/include/Poco/Net/HTTPBufferAllocator.h \
    poco/Net/include/Poco/Net/HTTPChunkedStream.h \
    poco/Net/include/Poco/Net/HTTPClientSession.h \
    poco/Net/include/Poco/Net/HTTPCookie.h \
    poco/Net/include/Poco/Net/HTTPCredentials.h \
    poco/Net/include/Poco/Net/HTTPDigestCredentials.h \
    poco/Net/include/Poco/Net/HTTPFixedLengthStream.h \
    poco/Net/include/Poco/Net/HTTPHeaderStream.h \
    poco/Net/include/Poco/Net/HTTPIOStream.h \
    poco/Net/include/Poco/Net/HTTPMessage.h \
    poco/Net/include/Poco/Net/HTTPNTLMCredentials.h \
    poco/Net/include/Poco/Net/HTTPRequest.h \
    poco/Net/include/Poco/Net/HTTPRequestHandler.h \
    poco/Net/include/Poco/Net/HTTPRequestHandlerFactory.h \
    poco/Net/include/Poco/Net/HTTPResponse.h \
    poco/Net/include/Poco/Net/HTTPServer.h \
    poco/Net/include/Poco/Net/HTTPServerConnection.h \
    poco/Net/include/Poco/Net/HTTPServerConnectionFactory.h \
    poco/Net/include/Poco/Net/HTTPServerParams.h \
    poco/Net/include/Poco/Net/HTTPServerRequest.h \
    poco/Net/include/Poco/Net/HTTPServerRequestImpl.h \
    poco/Net/include/Poco/Net/HTTPServerResponse.h \
    poco/Net/include/Poco/Net/HTTPServerResponseImpl.h \
    poco/Net/include/Poco/Net/HTTPServerSession.h \
    poco/Net/include/Poco/Net/HTTPSession.h \
    poco/Net/include/Poco/Net/HTTPSessionFactory.h \
    poco/Net/include/Poco/Net/HTTPSessionInstantiator.h \
    poco/Net/include/Poco/Net/HTTPStream.h \
    poco/Net/include/Poco/Net/HTTPStreamFactory.h \
    poco/Net/include/Poco/Net/HostEntry.h \
    poco/Net/include/Poco/Net/ICMPClient.h \
    poco/Net/include/Poco/Net/ICMPEventArgs.h \
    poco/Net/include/Poco/Net/ICMPPacket.h \
    poco/Net/include/Poco/Net/ICMPPacketImpl.h \
    poco/Net/include/Poco/Net/ICMPSocket.h \
    poco/Net/include/Poco/Net/ICMPSocketImpl.h \
    poco/Net/include/Poco/Net/ICMPv4PacketImpl.h \
    poco/Net/include/Poco/Net/IPAddress.h \
    poco/Net/include/Poco/Net/IPAddressImpl.h \
    poco/Net/include/Poco/Net/MailMessage.h \
    poco/Net/include/Poco/Net/MailRecipient.h \
    poco/Net/include/Poco/Net/MailStream.h \
    poco/Net/include/Poco/Net/MediaType.h \
    poco/Net/include/Poco/Net/MessageHeader.h \
    poco/Net/include/Poco/Net/MultiSocketPoller.h \
    poco/Net/include/Poco/Net/MulticastSocket.h \
    poco/Net/include/Poco/Net/MultipartReader.h \
    poco/Net/include/Poco/Net/MultipartWriter.h \
    poco/Net/include/Poco/Net/NTLMCredentials.h \
    poco/Net/include/Poco/Net/NTPClient.h \
    poco/Net/include/Poco/Net/NTPEventArgs.h \
    poco/Net/include/Poco/Net/NTPPacket.h \
    poco/Net/include/Poco/Net/NameValueCollection.h \
    poco/Net/include/Poco/Net/Net.h \
    poco/Net/include/Poco/Net/NetException.h \
    poco/Net/include/Poco/Net/NetworkInterface.h \
    poco/Net/include/Poco/Net/NullPartHandler.h \
    poco/Net/include/Poco/Net/OAuth10Credentials.h \
    poco/Net/include/Poco/Net/OAuth20Credentials.h \
    poco/Net/include/Poco/Net/POP3ClientSession.h \
    poco/Net/include/Poco/Net/ParallelSocketAcceptor.h \
    poco/Net/include/Poco/Net/ParallelSocketReactor.h \
    poco/Net/include/Poco/Net/PartHandler.h \
    poco/Net/include/Poco/Net/PartSource.h \
    poco/Net/include/Poco/Net/PartStore.h \
    poco/Net/include/Poco/Net/PollSet.h \
    poco/Net/include/Poco/Net/QuotedPrintableDecoder.h \
    poco/Net/include/Poco/Net/QuotedPrintableEncoder.h \
    poco/Net/include/Poco/Net/RawSocket.h \
    poco/Net/include/Poco/Net/RawSocketImpl.h \
    poco/Net/include/Poco/Net/RemoteSyslogChannel.h \
    poco/Net/include/Poco/Net/RemoteSyslogListener.h \
    poco/Net/include/Poco/Net/SMTPChannel.h \
    poco/Net/include/Poco/Net/SMTPClientSession.h \
    poco/Net/include/Poco/Net/SSPINTLMCredentials.h \
    poco/Net/include/Poco/Net/ServerSocket.h \
    poco/Net/include/Poco/Net/ServerSocketImpl.h \
    poco/Net/include/Poco/Net/SingleSocketPoller.h \
    poco/Net/include/Poco/Net/Socket.h \
    poco/Net/include/Poco/Net/SocketAcceptor.h \
    poco/Net/include/Poco/Net/SocketAddress.h \
    poco/Net/include/Poco/Net/SocketAddressImpl.h \
    poco/Net/include/Poco/Net/SocketConnector.h \
    poco/Net/include/Poco/Net/SocketDefs.h \
    poco/Net/include/Poco/Net/SocketImpl.h \
    poco/Net/include/Poco/Net/SocketNotification.h \
    poco/Net/include/Poco/Net/SocketNotifier.h \
    poco/Net/include/Poco/Net/SocketReactor.h \
    poco/Net/include/Poco/Net/SocketStream.h \
    poco/Net/include/Poco/Net/StreamSocket.h \
    poco/Net/include/Poco/Net/StreamSocketImpl.h \
    poco/Net/include/Poco/Net/StringPartSource.h \
    poco/Net/include/Poco/Net/TCPServer.h \
    poco/Net/include/Poco/Net/TCPServerConnection.h \
    poco/Net/include/Poco/Net/TCPServerConnectionFactory.h \
    poco/Net/include/Poco/Net/TCPServerDispatcher.h \
    poco/Net/include/Poco/Net/TCPServerParams.h \
    poco/Net/include/Poco/Net/UDPClient.h \
    poco/Net/include/Poco/Net/UDPHandler.h \
    poco/Net/include/Poco/Net/UDPServer.h \
    poco/Net/include/Poco/Net/UDPServerParams.h \
    poco/Net/include/Poco/Net/UDPSocketReader.h \
    poco/Net/include/Poco/Net/WebSocket.h \
    poco/Net/include/Poco/Net/WebSocketImpl.h \
    qtcpserver.h \
    solver.h \


